### PR TITLE
Speed up testing (Add test mode)

### PR DESCRIPTION
**Pull request by saito-tom**
I added test mode to coc and speed up the test.
Test mode actually blocks connections even if the result is ALLOW.
This is an option for coc development. (for testsuite)

# Motivation

- CIDR notation support (#1) increased the number of tests, so I wanted to speed up the test.
- I wanted to write a test without worrying about connecting to real IP.

# Test result of TEST_MODE

## No COC_TEST_MODE flag

The behavior of coc has not changed.

```
% ./coc -l allow -- ./tcpcontest 8.8.8.8 53
2018-10-03T05:54:47 ALLOW connection to 8.8.8.8:53
connect to 8.8.8.8 is OK

% ./coc -l allow -a "*" -- ./tcpcontest 8.8.8.8 53
2018-10-03T05:54:51 ALLOW connection to 8.8.8.8:53
connect to 8.8.8.8 is OK
```

## With COC_TEST_MODE flag

The message is ALLOW, but it does not actually connect.

```
% COC_TEST_MODE=1 ./coc -l allow -- ./tcpcontest 8.8.8.8 53
2018-10-03T05:54:55 ALLOW connection to 8.8.8.8:53
connect to 8.8.8.8 is KO: errno is 13 (Permission denied)

% COC_TEST_MODE=1 ./coc -l allow -a "*" -- ./tcpcontest 8.8.8.8 53
2018-10-03T05:55:00 ALLOW connection to 8.8.8.8:53
connect to 8.8.8.8 is KO: errno is 13 (Permission denied)
```

### CODE REVIEW

**Comment by saito-tom** [comment]
@tgg How about this? The test will be faster.

**Comment by tgg** [comment]
Hello,

sorry for the late reply.

How slow is the testing without it? 

While I understand the need, I am afraid this will affect the behavior if the environment variable is set unexpectedly.

Thanks,
Happy end of year,

Thomas

**Comment by saito-tom** [comment]
Thank you for your reply.

> While I understand the need, I am afraid this will affect the behavior if the environment variable is set unexpectedly.

I think that's right.
I have created a version that avoided that risk. (#6)
If you like #6, please close this #2 pull request.

> How slow is the testing without it?

I wrote the measurement result in #6 Benchmark. (132 sec -> 3 sec.)

Thanks,

**Comment by saito-tom** [comment]
I will close this pull request.
Please refer to #6.

**Pull request closed without merging**
